project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."

preserve_hierarchy: true

files:
  [
    {
      'source': '/src/i18n/locales/en-US/messages.json',
      'translation': '/src/i18n/locales/%locale%/%original_file_name%',
    },
  ]
