'\" t
.\"     Title: git-gc
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/16/2021
.\"    Manual: Git Manual
.\"    Source: Git 2.33.0
.\"  Language: English
.\"
.TH "GIT\-GC" "1" "08/16/2021" "Git 2\&.33\&.0" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-gc \- Cleanup unnecessary files and optimize the local repository
.SH "SYNOPSIS"
.sp
.nf
\fIgit gc\fR [\-\-aggressive] [\-\-auto] [\-\-quiet] [\-\-prune=<date> | \-\-no\-prune] [\-\-force] [\-\-keep\-largest\-pack]
.fi
.sp
.SH "DESCRIPTION"
.sp
Runs a number of housekeeping tasks within the current repository, such as compressing file revisions (to reduce disk space and increase performance), removing unreachable objects which may have been created from prior invocations of \fIgit add\fR, packing refs, pruning reflog, rerere metadata or stale working trees\&. May also update ancillary indexes such as the commit\-graph\&.
.sp
When common porcelain operations that create objects are run, they will check whether the repository has grown substantially since the last maintenance, and if so run \fBgit gc\fR automatically\&. See \fBgc\&.auto\fR below for how to disable this behavior\&.
.sp
Running \fBgit gc\fR manually should only be needed when adding objects to a repository without regularly running such porcelain commands, to do a one\-off repository optimization, or e\&.g\&. to clean up a suboptimal mass\-import\&. See the "PACKFILE OPTIMIZATION" section in \fBgit-fast-import\fR(1) for more details on the import case\&.
.SH "OPTIONS"
.PP
\-\-aggressive
.RS 4
Usually
\fIgit gc\fR
runs very quickly while providing good disk space utilization and performance\&. This option will cause
\fIgit gc\fR
to more aggressively optimize the repository at the expense of taking much more time\&. The effects of this optimization are mostly persistent\&. See the "AGGRESSIVE" section below for details\&.
.RE
.PP
\-\-auto
.RS 4
With this option,
\fIgit gc\fR
checks whether any housekeeping is required; if not, it exits without performing any work\&.
.sp
See the
\fBgc\&.auto\fR
option in the "CONFIGURATION" section below for how this heuristic works\&.
.sp
Once housekeeping is triggered by exceeding the limits of configuration options such as
\fBgc\&.auto\fR
and
\fBgc\&.autoPackLimit\fR, all other housekeeping tasks (e\&.g\&. rerere, working trees, reflog\&...) will be performed as well\&.
.RE
.PP
\-\-prune=<date>
.RS 4
Prune loose objects older than date (default is 2 weeks ago, overridable by the config variable
\fBgc\&.pruneExpire\fR)\&. \-\-prune=now prunes loose objects regardless of their age and increases the risk of corruption if another process is writing to the repository concurrently; see "NOTES" below\&. \-\-prune is on by default\&.
.RE
.PP
\-\-no\-prune
.RS 4
Do not prune any loose objects\&.
.RE
.PP
\-\-quiet
.RS 4
Suppress all progress reports\&.
.RE
.PP
\-\-force
.RS 4
Force
\fBgit gc\fR
to run even if there may be another
\fBgit gc\fR
instance running on this repository\&.
.RE
.PP
\-\-keep\-largest\-pack
.RS 4
All packs except the largest pack and those marked with a
\fB\&.keep\fR
files are consolidated into a single pack\&. When this option is used,
\fBgc\&.bigPackThreshold\fR
is ignored\&.
.RE
.SH "AGGRESSIVE"
.sp
When the \fB\-\-aggressive\fR option is supplied, \fBgit-repack\fR(1) will be invoked with the \fB\-f\fR flag, which in turn will pass \fB\-\-no\-reuse\-delta\fR to \fBgit-pack-objects\fR(1)\&. This will throw away any existing deltas and re\-compute them, at the expense of spending much more time on the repacking\&.
.sp
The effects of this are mostly persistent, e\&.g\&. when packs and loose objects are coalesced into one another pack the existing deltas in that pack might get re\-used, but there are also various cases where we might pick a sub\-optimal delta from a newer pack instead\&.
.sp
Furthermore, supplying \fB\-\-aggressive\fR will tweak the \fB\-\-depth\fR and \fB\-\-window\fR options passed to \fBgit-repack\fR(1)\&. See the \fBgc\&.aggressiveDepth\fR and \fBgc\&.aggressiveWindow\fR settings below\&. By using a larger window size we\(cqre more likely to find more optimal deltas\&.
.sp
It\(cqs probably not worth it to use this option on a given repository without running tailored performance benchmarks on it\&. It takes a lot more time, and the resulting space/delta optimization may or may not be worth it\&. Not using this at all is the right trade\-off for most users and their repositories\&.
.SH "CONFIGURATION"
.sp
The below documentation is the same as what\(cqs found in \fBgit-config\fR(1):
.PP
gc\&.aggressiveDepth
.RS 4
The depth parameter used in the delta compression algorithm used by
\fIgit gc \-\-aggressive\fR\&. This defaults to 50, which is the default for the
\fB\-\-depth\fR
option when
\fB\-\-aggressive\fR
isn\(cqt in use\&.
.sp
See the documentation for the
\fB\-\-depth\fR
option in
\fBgit-repack\fR(1)
for more details\&.
.RE
.PP
gc\&.aggressiveWindow
.RS 4
The window size parameter used in the delta compression algorithm used by
\fIgit gc \-\-aggressive\fR\&. This defaults to 250, which is a much more aggressive window size than the default
\fB\-\-window\fR
of 10\&.
.sp
See the documentation for the
\fB\-\-window\fR
option in
\fBgit-repack\fR(1)
for more details\&.
.RE
.PP
gc\&.auto
.RS 4
When there are approximately more than this many loose objects in the repository,
\fBgit gc \-\-auto\fR
will pack them\&. Some Porcelain commands use this command to perform a light\-weight garbage collection from time to time\&. The default value is 6700\&.
.sp
Setting this to 0 disables not only automatic packing based on the number of loose objects, but any other heuristic
\fBgit gc \-\-auto\fR
will otherwise use to determine if there\(cqs work to do, such as
\fBgc\&.autoPackLimit\fR\&.
.RE
.PP
gc\&.autoPackLimit
.RS 4
When there are more than this many packs that are not marked with
\fB*\&.keep\fR
file in the repository,
\fBgit gc \-\-auto\fR
consolidates them into one larger pack\&. The default value is 50\&. Setting this to 0 disables it\&. Setting
\fBgc\&.auto\fR
to 0 will also disable this\&.
.sp
See the
\fBgc\&.bigPackThreshold\fR
configuration variable below\&. When in use, it\(cqll affect how the auto pack limit works\&.
.RE
.PP
gc\&.autoDetach
.RS 4
Make
\fBgit gc \-\-auto\fR
return immediately and run in background if the system supports it\&. Default is true\&.
.RE
.PP
gc\&.bigPackThreshold
.RS 4
If non\-zero, all packs larger than this limit are kept when
\fBgit gc\fR
is run\&. This is very similar to
\fB\-\-keep\-largest\-pack\fR
except that all packs that meet the threshold are kept, not just the largest pack\&. Defaults to zero\&. Common unit suffixes of
\fIk\fR,
\fIm\fR, or
\fIg\fR
are supported\&.
.sp
Note that if the number of kept packs is more than gc\&.autoPackLimit, this configuration variable is ignored, all packs except the base pack will be repacked\&. After this the number of packs should go below gc\&.autoPackLimit and gc\&.bigPackThreshold should be respected again\&.
.sp
If the amount of memory estimated for
\fBgit repack\fR
to run smoothly is not available and
\fBgc\&.bigPackThreshold\fR
is not set, the largest pack will also be excluded (this is the equivalent of running
\fBgit gc\fR
with
\fB\-\-keep\-largest\-pack\fR)\&.
.RE
.PP
gc\&.writeCommitGraph
.RS 4
If true, then gc will rewrite the commit\-graph file when
\fBgit-gc\fR(1)
is run\&. When using
\fBgit gc \-\-auto\fR
the commit\-graph will be updated if housekeeping is required\&. Default is true\&. See
\fBgit-commit-graph\fR(1)
for details\&.
.RE
.PP
gc\&.logExpiry
.RS 4
If the file gc\&.log exists, then
\fBgit gc \-\-auto\fR
will print its content and exit with status zero instead of running unless that file is more than
\fIgc\&.logExpiry\fR
old\&. Default is "1\&.day"\&. See
\fBgc\&.pruneExpire\fR
for more ways to specify its value\&.
.RE
.PP
gc\&.packRefs
.RS 4
Running
\fBgit pack\-refs\fR
in a repository renders it unclonable by Git versions prior to 1\&.5\&.1\&.2 over dumb transports such as HTTP\&. This variable determines whether
\fIgit gc\fR
runs
\fBgit pack\-refs\fR\&. This can be set to
\fBnotbare\fR
to enable it within all non\-bare repos or it can be set to a boolean value\&. The default is
\fBtrue\fR\&.
.RE
.PP
gc\&.pruneExpire
.RS 4
When
\fIgit gc\fR
is run, it will call
\fIprune \-\-expire 2\&.weeks\&.ago\fR\&. Override the grace period with this config variable\&. The value "now" may be used to disable this grace period and always prune unreachable objects immediately, or "never" may be used to suppress pruning\&. This feature helps prevent corruption when
\fIgit gc\fR
runs concurrently with another process writing to the repository; see the "NOTES" section of
\fBgit-gc\fR(1)\&.
.RE
.PP
gc\&.worktreePruneExpire
.RS 4
When
\fIgit gc\fR
is run, it calls
\fIgit worktree prune \-\-expire 3\&.months\&.ago\fR\&. This config variable can be used to set a different grace period\&. The value "now" may be used to disable the grace period and prune
\fB$GIT_DIR/worktrees\fR
immediately, or "never" may be used to suppress pruning\&.
.RE
.PP
gc\&.reflogExpire, gc\&.<pattern>\&.reflogExpire
.RS 4
\fIgit reflog expire\fR
removes reflog entries older than this time; defaults to 90 days\&. The value "now" expires all entries immediately, and "never" suppresses expiration altogether\&. With "<pattern>" (e\&.g\&. "refs/stash") in the middle the setting applies only to the refs that match the <pattern>\&.
.RE
.PP
gc\&.reflogExpireUnreachable, gc\&.<pattern>\&.reflogExpireUnreachable
.RS 4
\fIgit reflog expire\fR
removes reflog entries older than this time and are not reachable from the current tip; defaults to 30 days\&. The value "now" expires all entries immediately, and "never" suppresses expiration altogether\&. With "<pattern>" (e\&.g\&. "refs/stash") in the middle, the setting applies only to the refs that match the <pattern>\&.
.sp
These types of entries are generally created as a result of using
\fBgit commit \-\-amend\fR
or
\fBgit rebase\fR
and are the commits prior to the amend or rebase occurring\&. Since these changes are not part of the current project most users will want to expire them sooner, which is why the default is more aggressive than
\fBgc\&.reflogExpire\fR\&.
.RE
.PP
gc\&.rerereResolved
.RS 4
Records of conflicted merge you resolved earlier are kept for this many days when
\fIgit rerere gc\fR
is run\&. You can also use more human\-readable "1\&.month\&.ago", etc\&. The default is 60 days\&. See
\fBgit-rerere\fR(1)\&.
.RE
.PP
gc\&.rerereUnresolved
.RS 4
Records of conflicted merge you have not resolved are kept for this many days when
\fIgit rerere gc\fR
is run\&. You can also use more human\-readable "1\&.month\&.ago", etc\&. The default is 15 days\&. See
\fBgit-rerere\fR(1)\&.
.RE
.SH "NOTES"
.sp
\fIgit gc\fR tries very hard not to delete objects that are referenced anywhere in your repository\&. In particular, it will keep not only objects referenced by your current set of branches and tags, but also objects referenced by the index, remote\-tracking branches, reflogs (which may reference commits in branches that were later amended or rewound), and anything else in the refs/* namespace\&. Note that a note (of the kind created by \fIgit notes\fR) attached to an object does not contribute in keeping the object alive\&. If you are expecting some objects to be deleted and they aren\(cqt, check all of those locations and decide whether it makes sense in your case to remove those references\&.
.sp
On the other hand, when \fIgit gc\fR runs concurrently with another process, there is a risk of it deleting an object that the other process is using but hasn\(cqt created a reference to\&. This may just cause the other process to fail or may corrupt the repository if the other process later adds a reference to the deleted object\&. Git has two features that significantly mitigate this problem:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Any object with modification time newer than the
\fB\-\-prune\fR
date is kept, along with everything reachable from it\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Most operations that add an object to the database update the modification time of the object if it is already present so that #1 applies\&.
.RE
.sp
However, these features fall short of a complete solution, so users who run commands concurrently have to live with some risk of corruption (which seems to be low in practice)\&.
.SH "HOOKS"
.sp
The \fIgit gc \-\-auto\fR command will run the \fIpre\-auto\-gc\fR hook\&. See \fBgithooks\fR(5) for more information\&.
.SH "SEE ALSO"
.sp
\fBgit-prune\fR(1) \fBgit-reflog\fR(1) \fBgit-repack\fR(1) \fBgit-rerere\fR(1)
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
