'\" t
.\"     Title: git-column
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/08/2021
.\"    Manual: Git Manual
.\"    Source: Git 2.30.1
.\"  Language: English
.\"
.TH "GIT\-COLUMN" "1" "02/08/2021" "Git 2\&.30\&.1" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-column \- Display data in columns
.SH "SYNOPSIS"
.sp
.nf
\fIgit column\fR [\-\-command=<name>] [\-\-[raw\-]mode=<mode>] [\-\-width=<width>]
             [\-\-indent=<string>] [\-\-nl=<string>] [\-\-padding=<n>]
.fi
.sp
.SH "DESCRIPTION"
.sp
This command formats the lines of its standard input into a table with multiple columns\&. Each input line occupies one cell of the table\&. It is used internally by other git commands to format output into columns\&.
.SH "OPTIONS"
.PP
\-\-command=<name>
.RS 4
Look up layout mode using configuration variable column\&.<name> and column\&.ui\&.
.RE
.PP
\-\-mode=<mode>
.RS 4
Specify layout mode\&. See configuration variable column\&.ui for option syntax in
\fBgit-config\fR(1)\&.
.RE
.PP
\-\-raw\-mode=<n>
.RS 4
Same as \-\-mode but take mode encoded as a number\&. This is mainly used by other commands that have already parsed layout mode\&.
.RE
.PP
\-\-width=<width>
.RS 4
Specify the terminal width\&. By default
\fIgit column\fR
will detect the terminal width, or fall back to 80 if it is unable to do so\&.
.RE
.PP
\-\-indent=<string>
.RS 4
String to be printed at the beginning of each line\&.
.RE
.PP
\-\-nl=<N>
.RS 4
String to be printed at the end of each line, including newline character\&.
.RE
.PP
\-\-padding=<N>
.RS 4
The number of spaces between columns\&. One space by default\&.
.RE
.SH "EXAMPLES"
.sp
Format data by columns:
.sp
.if n \{\
.RS 4
.\}
.nf
$ seq 1 24 | git column \-\-mode=column \-\-padding=5
1      4      7      10     13     16     19     22
2      5      8      11     14     17     20     23
3      6      9      12     15     18     21     24
.fi
.if n \{\
.RE
.\}
.sp
.sp
Format data by rows:
.sp
.if n \{\
.RS 4
.\}
.nf
$ seq 1 21 | git column \-\-mode=row \-\-padding=5
1      2      3      4      5      6      7
8      9      10     11     12     13     14
15     16     17     18     19     20     21
.fi
.if n \{\
.RE
.\}
.sp
.sp
List some tags in a table with unequal column widths:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git tag \-\-list \*(Aqv2\&.4\&.*\*(Aq \-\-column=row,dense
v2\&.4\&.0  v2\&.4\&.0\-rc0  v2\&.4\&.0\-rc1  v2\&.4\&.0\-rc2  v2\&.4\&.0\-rc3
v2\&.4\&.1  v2\&.4\&.10     v2\&.4\&.11     v2\&.4\&.12     v2\&.4\&.2
v2\&.4\&.3  v2\&.4\&.4      v2\&.4\&.5      v2\&.4\&.6      v2\&.4\&.7
v2\&.4\&.8  v2\&.4\&.9
.fi
.if n \{\
.RE
.\}
.sp
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
