name: Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-2019, ubuntu-latest ]

    steps:
      - name: Setup apt dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends -y libarchive-tools rpm

      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6

      - name: Install dependencies
        run: |
          yarn install --network-timeout 180000

      - name: yarn lint
        run: |
          yarn lint

      - name: yarn package
        run: |
          yarn package

      - name: yarn test
        run: |
          yarn test

